import type { Metadata } from "next";
import { Montserrat, Lato } from "next/font/google";
import "./globals.css";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

const lato = Lato({
  variable: "--font-lato",
  weight: ["400", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${montserrat.variable} ${lato.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {/* Nav */}
        <nav aria-label="Main navigation" className="bg-[#1C3B3A] sticky top-0 z-50">
          <a
            href="#main-content"
            className="sr-only focus:not-sr-only focus:fixed focus:top-4 focus:left-4 focus:z-[100] focus:bg-amber focus:text-white focus:px-4 focus:py-2 focus:rounded-md focus:font-medium"
          >
            Skip to main content
          </a>
          <div className="max-w-6xl mx-auto px-6 py-5 flex items-center justify-between">
            <div>
              <div className="font-heading font-bold text-[#F9F4EC] text-4xl tracking-tight">TJRCS</div>
              <div className="font-sans text-[#F9F4EC] text-sm leading-tight mt-1">Tamika Jackson Recreation and Consulting Services</div>
            </div>
            <div className="flex gap-4">
              <a href="/" className="text-[#F9F4EC] text-base font-bold border-2 border-[#E8924B] bg-transparent px-4 py-2 rounded-full hover:bg-[#E8924B] hover:text-[#1C3B3A] transition-colors focus-visible:outline-2 focus-visible:outline-[#F9F4EC] focus-visible:outline-offset-2">Home</a>
              <a href="#about" className="text-[#F9F4EC] text-base font-bold border-2 border-[#E8924B] bg-transparent px-4 py-2 rounded-full hover:bg-[#E8924B] hover:text-[#1C3B3A] transition-colors focus-visible:outline-2 focus-visible:outline-[#F9F4EC] focus-visible:outline-offset-2">About</a>
              <a href="#contact" className="text-[#F9F4EC] text-base font-bold border-2 border-[#E8924B] bg-transparent px-4 py-2 rounded-full hover:bg-[#E8924B] hover:text-[#1C3B3A] transition-colors focus-visible:outline-2 focus-visible:outline-[#F9F4EC] focus-visible:outline-offset-2">Contact</a>
            </div>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
